# Generated by Django 3.2 on 2023-01-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqama_id', models.CharField(max_length=20)),
                ('SCFHS', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('job_position', models.CharField(choices=[('resident', 'Resident'), ('specialist', 'Specialist'), ('consultant', 'Consultant')], max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
